version: "3.7"
services:
  django: 
    build:
      context: .
      dockerfile: Dockerfile
    command: python /src/manage.py runserver 0.0.0.0:8000
    ports: 
      - 4000:8000
    volumes:
      - .:/src
