# Generated by Django 4.0.5 on 2022-06-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Track',
        ),
    ]
