# Generated by Django 4.0.5 on 2022-06-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_rename_book_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
