# Generated by Django 4.0.5 on 2022-06-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_audio_file_alter_track_artwork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
