# Generated by Django 4.0.5 on 2022-06-22 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_track_dislikes_track_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='id',
        ),
        migrations.AddField(
            model_name='track',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
