# Generated by Django 4.0.5 on 2022-06-22 21:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_remove_track_id_track_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='ID',
        ),
        migrations.AddField(
            model_name='track',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
