name: dlvr-build-master-container
on: 
  push: 
    branches: 
      - "main"
  workflow_dispatch:
jobs:
  push_to_registry:
    name: push docker image to docker hub
  runs-on: ubuntu-latest
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with: 
        context: back
        push: true
        tags: anthariajack/dlvr:latest
